// Regenerates public/icons/favicon-{16,32}.png and apple-touch-icon.png
// from the two master images below -- the real brand brain glyph, laid
// out two ways and exported once at 512x512 each. Downscales with
// macOS's built-in `sips` -- no image-processing dependency (no
// sharp/canvas), same reasoning as extension/generate-icons.js.
//
//  - master-favicon.png: transparent background, tight padding. Used for
//    the small favicon PNGs.
//  - master-any.png: white background, generous padding. Used for
//    apple-touch-icon -- same look as the extension icons.
//
// favicon.ico itself is NOT generated by this script -- sips lists "ico"
// under --formats but can't actually write one (tested; fails with
// "Error 13: an unknown error occurred"), and packing a proper
// multi-resolution ICO needs a real image library this project
// deliberately doesn't depend on. It's checked in as a static asset;
// regenerate it by hand (e.g. from master-favicon.png via any ICO tool)
// if the art changes.
//
// macOS-only (sips isn't available elsewhere) -- there's no CI/build
// step depending on this, it's a one-off run-by-hand generator. To
// update the icon art itself, replace the two master-*.png files (keep
// them square) and rerun this script.
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const outDir = path.join(__dirname, 'public', 'icons');

function resize(masterName, outName, size) {
  const masterPath = path.join(outDir, masterName);
  const outPath = path.join(outDir, outName);
  execFileSync('sips', ['-z', String(size), String(size), masterPath, '--out', outPath], { stdio: 'ignore' });
  console.log(`wrote public/icons/${outName} (${size}x${size})`);
}

resize('master-favicon.png', 'favicon-16.png', 16);
resize('master-favicon.png', 'favicon-32.png', 32);
resize('master-any.png', 'apple-touch-icon.png', 180);
